# 2. Gram-Schmidt orthonormalization

### Exercise

$$
x_1 = \begin{bmatrix} 3\\6\\2\end{bmatrix}, x_2 = \begin{bmatrix} 1\\2\\4\end{bmatrix}, x_3 = \begin{bmatrix} 2\\-2\\1\end{bmatrix}
$$

$$v_1 = x_1 \\ u_1 = \frac{v_1}{||v_1||}$$

$$ \hat{x_2} = \text{Proj}_{\mathcal{W_1}}x_2 = \frac{x_2 \cdot u_1}{u_1 \cdot u_1}u_1 \\
v_2 = x_2 - \hat{x_2} = x_2 -  \frac{x_2 \cdot u_1}{u_1 \cdot u_1}u_1 \\
u_2 = \frac{v_2}{||v_2||}
$$

$$ \hat{x_3} = \text{Proj}_{\mathcal{W_2}}x_3 = \frac{x_3 \cdot u_1}{u_1 \cdot u_1}u_1  + \frac{x_3 \cdot u_2}{u_2 \cdot u_2}u_2 \\
v_3 = x_3 - \hat{x_3} = x_3 -  \frac{x_3 \cdot u_1}{u_1 \cdot u_1}u_1  - \frac{x_3 \cdot u_2}{u_2 \cdot u_2}u_2 \\
u_3 = \frac{v_3}{||v_3||}
$$

In [29]:
import numpy as np
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

x1 = np.array([3, 6, 2])
x2 = np.array([1, 2, 4])
x3 = np.array([2, -2, 1])

v1 = x1 
u1 = v1/np.linalg.norm(v1)
print(u1@u1) # 문제가 생기는 부분
x2_hat = (x2@u1)/(u1@u1)*u1
v2 = x2_hat - x2
u2 = v2/np.linalg.norm(v2)
print(f"u1 @ u2 = {u1 @ u2} (0의 근사치)")
print(f"x2_hat @ u2 = {x2_hat @ u2} (0의 근사치)")


0.9999999999999999
u1 @ u2 = -2.7755575615628914e-17 (0의 근사치)
x2_hat @ u2 = -1.1102230246251565e-16 (0의 근사치)


In [25]:

x3_hat = (x3@u1)/(u1@u1)*u1 + (x3@u2)/(u2@u2)*u2
v3 = x3 - x3_hat
u3 = v3/np.linalg.norm(v3)

print(f"u1 @ u3 = {u1 @ u3}")
print(f"u2 @ u3 = {u2 @ u3}")
print(f"x3_hat @ u3 = {x3_hat @ u3}")

u1 @ u3 = 0.0
u2 @ u3 = 0.0
x3_hat @ u3 = 0.0


# 3. QR decomposition

### Exercise

위의 예시를 가져옵시다.

* Matrix $A = \begin{bmatrix} 3&1&2\\6&2&-2\\2&4&1\end{bmatrix}$라고 할 때, 위의 Gram-Schmidt된 결과를 이용해서 A를 QR decompose 하시오 (hint: 아래 수식을 이용하시오).

$$ 
u_1 = \frac{v_1}{||v_1||} \rightarrow x_1 = ||v_1|| \; u_1
\\
u_2 = \frac{v_2}{||v_2||} = \frac{x_2 -  \frac{x_2 \cdot u_1}{u_1 \cdot u_1}u_1}{||v_2||} \rightarrow x_2 = \frac{x_2 \cdot u_1}{u_1 \cdot u_1}u_1 + ||v_2|| \; u_2
\\
u_3 = \frac{v_3}{||v_3||} =  \frac{x_3 -  \frac{x_3 \cdot u_1}{u_1 \cdot u_1}u_1  - \frac{x_3 \cdot u_2}{u_2 \cdot u_2}u_2 }{||v_3||} \rightarrow x_3 = \frac{x_3 \cdot u_1}{u_1 \cdot u_1}u_1 + \frac{x_3 \cdot u_2}{u_2 \cdot u_2}u_2 + ||v_3|| \; u_3  \\
$$

In [21]:
A = np.array([[3,1,2],[6,2,-2],[2,4,1]])
Q = np.array([u1,u2,u3]).T
R = np.linalg.inv(Q)@A
Q, R

(array([[ 0.429,  0.128,  0.894],
        [ 0.857,  0.256, -0.447],
        [ 0.286, -0.958,  0.   ]]),
 array([[ 7.   ,  3.286, -0.571],
        [ 0.   , -3.194, -1.214],
        [ 0.   ,  0.   ,  2.683]]))

In [22]:
Q, R = np.linalg.qr(A)
Q, R

(array([[-0.429, -0.128, -0.894],
        [-0.857, -0.256,  0.447],
        [-0.286,  0.958, -0.   ]]),
 array([[-7.   , -3.286,  0.571],
        [ 0.   ,  3.194,  1.214],
        [ 0.   ,  0.   , -2.683]]))