# Linear Algebra Quiz1

> 해당 퀴즈에서는 강의에서 직접적으로 다루지 않은 문제들도 포함되어 있습니다. 성취도 확인용으로 진행되는 시험이니 한 주 동안 배운 내용을 복습하고 새로운 문제들을 공부하는 데 의미를 두시면 좋을 것 같습니다. 계산이 필요할 경우 손으로 계산하셔도 되고, 각자 colab을 켜서 numpy 등의 package를 사용하셔도 됩니다.

In [25]:
import sympy as sy
import numpy as np
a1,a2,a3,a4,a5,a6,a7,a8,a9,b1,b2,b3,b4,b5,b6,b7,b8,b9,c1,c2,d1,d2 = sy.symbols('a1,a2,a3,a4,a5,a6,a7,a8,a9,b1,b2,b3,b4,b5,b6,b7,b8,b9,c1,c2,d1,d2')

## 다음 명제에 대해, True/False를 판단하시오. True일 경우 간략하게 이유를 서술하고, False일 경우 간략하게 이유를 설명하거나 반례를 드시오.

\\

행렬 $A,B$에 대해

\\

1. $A$와 $B$가 invertible 하다면, $(AB)^{-1} = A^{-1}B^{-1}$이 성립한다. \\



A: False

양 변에 AB를 곱해주면 $I == ABA^{-1}B^{-1}$
이어야 되지만 이는 성립하지 않을 경우가 존재한다.
밑의 예시를 봐도 그렇다.

In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
AB = A@B
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
AB_inv = np.linalg.inv(AB)
A_invB_inv = A_inv@B_inv
AB_inv, A_invB_inv

(array([[ 12.5 ,  -5.5 ],
        [-10.75,   4.75]]),
 array([[11.5 , -8.5 ],
        [-7.75,  5.75]]))


---



2. $\begin{bmatrix} 1 & 1 \\ 0 & 1 \\ 0 & 0 \end{bmatrix} \begin{bmatrix}x1\\x2\end{bmatrix} = \begin{bmatrix} 3 \\ 1 \\ 0\end{bmatrix}$는 해가 존재한다. \\

A: True

해당 계산을 colum vector equation으로 생각하면 (1,0,0) 과 (1,1,0) 로 만든 span에 (3,1,0) vector 가 linearly dependent 하기 때문에 해가 존재한다.



---



3. $\begin{bmatrix} 1 & 1 \\ 0 & 1 \\ 0 & 0 \end{bmatrix} \begin{bmatrix}x1\\x2\end{bmatrix} = \begin{bmatrix} 3 \\ 1 \\ 1\end{bmatrix}$은 해가 존재한다. \\


A: False

해당 계산을 colum vector equation으로 생각하면 (1,0,0) 과 (1,1,0) 로 만든 span에 (3,1,1) vector 가 linearly independent 하기 때문에 해가 존재하지 않는다.

---



4. $\begin{bmatrix} 3 & 2 \\ 5 & 1 \\ 0 & 0 \end{bmatrix}$의 column space는 span($\{ \begin{bmatrix} 1 \\ 0 \\ 0\end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 0\end{bmatrix}\}$)과 같다. \\

A: True

(3,5,0)을 a 백터로 (2,1,0)을 b 백터로 생각하고 (1,0,0)을 i (0,1,0)을 j로 생각했을때, a = 3i + 5j, b = 2i + 1j로 모두 i, j에 linearly dependent하기 때문에 span은 같다.

---



5. $R^2$는 $R^3$의 subspace이다.

A: ~~True~~ False

$R^2$ 안에서 어떻게 선형결합을 하더라도 $R^3$ 안에 속하게 된다.

---



6. Vector $x \in R^2$에 대한 Transformation $T_1$: (1) x축에 대해 reflection 후 (2) y축에 대해 reflection. \\
 Vector $x \in R^2$에 대한 Transformatiopn $T_2$: 시계방향으로 180도 회전. \\
 이때 $T_1$은 $T_2$와 같다. \\

A: True

x축에 대한 reflection을 시키는 행렬을 $X$ y축에 대한 reflection을 시키는 행렬을 $Y$
시계방향으로 180도 회전을 시키는 행렬을 $Z$ 라고 하자.

이때 $T1$ 은 좌표계 A에 $(YX)A$ 를 하면 되고

$T2$ 는 좌표계 A에 $ZA$ 를 하면 된다.

이때 $Y = \begin{bmatrix} -1 & 0 \\ 0 & 1 \end{bmatrix}$  $X = \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}$ $YX = \begin{bmatrix} -1 & 0 \\ 0 & -1 \end{bmatrix}$

$Z = \begin{bmatrix} -1 & 0 \\ 0 & -1 \end{bmatrix}$ 이기 때문에 $T1 == T2$ 이다

---



7. A,B가 각각 invertible하면, $(A+B)^{-1} = A^{-1} + B^{-1}$ 이다.

A: False

역행렬 연산은 덧셈에 대한 분배법칙이 성립하지 않는다.



---



8. $T(x) = Ax = \begin{bmatrix} 3 & 2 \\ 5 & 1 \\ 0 & 0 \end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}$는 $R^2$에서 $R^3$으로 ONTO mapping하는 transformation이다.

A: False

A를 이용해서 x1, x2를 mapping할 때, z축에 대한 mapping이 되지 않기 때문에 ONTO 하지 않다.



---



9. $T(x) = Ax = \begin{bmatrix} 3 & 2 \\ 5 & 1 \\ 0 & 0 \end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}$는 $R^2$에서 $R^3$으로 one-to-one mapping하는 transformation이다.

A: True

A의 두 linear column이 linearly independent하기 때문에 one-to-one이다.

---



10. $T(x) = Ax = \begin{bmatrix} 1 & 0 &0&5&0\\ 0 & 1 &0&1&0\\ 0 & 0&1&0&0\\0&0&0&0&1 \end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\\x_4\\x_5\end{bmatrix}$는 $R^5$에서 $R^4$으로 ONTO mapping하는 transformation이다.

A: True

A의 linear column vector의 linear combination으로 R4 전체를 표현할 수 있기 때문에 ONTO mapping하는 transformation이다.

---



11. $T(x) = Ax = \begin{bmatrix} 1 & 0 &0&5&0\\ 0 & 1 &0&1&0\\ 0 & 0&1&0&0\\0&0&0&0&1 \end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\\x_4\\x_5\end{bmatrix}$는 $R^5$에서 $R^4$으로 one-to-one mapping하는 transformation이다.

A: False

4번째 열의 linear column vector가 linearly  dependent하기 때문에 one-to-one mapping이 불가능하다.

---



12. $T: R^n \rightarrow R^n$ 인 $T$가 one-to-one linear transformation이면, $T$는 ONTO linear transformation이다.

A: True

n by n 행렬 T 의 linear column vector가 서로 linearly independent하면 ONTO 하다.

---



13. $T: R^n \rightarrow R^n$ 인 $T$가 ONTO linear transformation이면, $T$는 one-to-one linear transformation이다.

A: True

n by n 행렬이 ONTO 하게 되면 linearly dependent해야 되기 때문에 one-to-one하다

---



14. $A$가 $n \times n$ matrix이면서 rank가 $n$인 경우, $A$는 invertible 하다.

A: True

A가 invertible하려면 서로 linearly independent하기 때문에 해당 matrix는 rank가 n이게 된다.

---



15. $A = \begin{bmatrix} 1 & 1 & 1\\ 2 & 2& 2 \\ 3 & 3& 3 \end{bmatrix}$은 invertible하지 않다.

A: True

해당 matrix는 linearly dependent하기 때문에 invertible하지 않다.

---



16. $A$와 $B$의 rank가 같다면, 두 matrix의 shape은 같다.

A. False

rank가 같더라도 해당 matrix를 구성하는 linear vector는 linear dependent 한 linear vector가 추가 될 수 있다.

---



17. $AB = BC$이면, $B=C$이다.

A: False

---



18. $B = A^TA$이면, $B$는 symmetric matrix이다.

A: True

transpose는 분배법칙에 의해서 $ (A^{T}A)^{T} = A^{T}A $ 이다.

---



19. Vector $v_1, v_2, v_3, v_4, v_5$가 $R^5$를 span한다면, 저 다섯 vector는 서로 linearly independent하다.

A. True

만약 linearly dependent한 vector가 생기면 rank가 5가 될 수 없다.

---



20. $v_1, v_2, v_3 \in R^3$인 세 vector가 서로 linearly dependent 하다면, 세 vector를 칼럼으로 하는 matrix $A = \begin{bmatrix} \mid & \mid & \mid \\ v_1 & v_2 & v_3 \\ \mid & \mid & \mid  \end{bmatrix}$는 invertible하지 않다.

A. True

이때, $Ax = b$ 의 해는 하나로 정해지지 않기 때문에 invertible 하지 않다

---



21. $v_1, v_2 \in R^3$인 두 vector가 span하는 subspace는 평면이다 (2 dimensional subspace).

A. False

$ v1, v2 $ 가 linearly dependent하게 된다면 1 dimension도 가능하다.

---



22. Normal equation은 해가 항상 존재한다.

A True

어떠한 space A에 대한 수선의 발은 무조건 존재하기 때문에 해는 항상 존재하게 된다.

---



23. $m \times n$ matrix $A$의 column vector $v_1,v_2, \cdots, v_n$이 orthonormal 하다면,  $AA^Tx$는 $x$를 Col $A$에 orthogonal projection하는 matrix이다.

 A. True

 $A(A^{T}A)^{-1}A^{T}$ 에서 $A^{T}A == I$ 이기 때문에.

---



24. $m \times n$ matrix $A$의 column vector $v_1,v_2, \cdots, v_n$이 서로 linearly independent 하다고 하자. 그렇다면 $v_1,v_2, \cdots, v_n$에 Gram-Schmidt를 적용하면 Col $A$의 orthogonal basis가 된다.

A. True



---



25. Subspace $V$ = span ($\Bigg\{ \begin{bmatrix} 3 \\ 1 \\ 0\end{bmatrix}\, \begin{bmatrix} 1 \\ 2 \\ 0\end{bmatrix}\Bigg\}$)라고 하자. 이때 ($\Bigg\{ \begin{bmatrix} 1 \\ 1 \\ 0\end{bmatrix}\, \begin{bmatrix} 0 \\ 0 \\ 1\end{bmatrix}\Bigg\}$)은 $V$의 orthogonal basis가 된다.

A. False

V는 $R^2$ 의 span이지만 $\Bigg\{ \begin{bmatrix} 1 \\ 1 \\ 0\end{bmatrix}\, \begin{bmatrix} 0 \\ 0 \\ 1\end{bmatrix}\Bigg\}$ 의 span은 $ R^3 $ 이다


In [28]:
A = np.array([[3,1],[1,2],[0,0]])
Q, R = np.linalg.qr(A)
Q

array([[-0.9486833 , -0.31622777],
       [-0.31622777,  0.9486833 ],
       [-0.        , -0.        ]])


---



26. 어떤 임의의 n개의 vector set이 주어졌을 때, Gram-Schmidt orthonormalization을 이용하면, 서로 orthonormal한 n개의 vector set으로 만들 수 있다.

A. False

이때 vector set에서 dependent한 set가 존재할 수 있기 때문에 서로 orthonormal한 n개의 vector set이 되지 않을 수 있다.

---



27. $A^TA=0$이면, $A=0$이다.

A. True

$A^TA$ 에서 0,0이나 1,1은 각 column vector의 길이이기 때문에 0이어야 성립

---



___

28 ~ 32 연산을 해서 닫혀있는지 확인하는 방식으로 subspace인지 확인한다.

___

28.  $x_1=x_3$를 만족하는 vector $x=\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}$의 set을 $H$라고 하자. $H$는 $R^3$의 subspace이다.

A. ~~False~~ True

x1과 x3가 같기 때문에 $R^2$ 의 subspace이다.

---

29. $x_2=1$를 만족하는 vector $x=\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}$의 set을 $H$라고 하자. $H$는 $R^3$의 subspace이다.


A. False

x2가 1이기 때문에 x1과 x3로만 구성된 $R^2$ 의 subspace이다.

---



30. $x_1x_2=0$를 만족하는 vector $x=\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}$의 set을 $H$라고 하자. $H$는 $R^3$의 subspace이다.


A. ~~True~~ False

$\begin{bmatrix}1\\0\\0\end{bmatrix}\begin{bmatrix}0\\1\\0\end{bmatrix}\begin{bmatrix}0\\0\\1\end{bmatrix}$ 도 $x_1x_2=0$를 만족하면서 $R^3$ 의 subspace이다.

---



31. $x_1+x_2+x_3=0$를 만족하는 vector $x=\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}$의 set을 $H$라고 하자. $H$는 $R^3$의 subspace이다.


A. True

$x_1+x_2+x_3=0$를 만족하면서 linearly independent한 3개의 column vector를 만들 수 있기 때문이다.

---



32. span $\Bigg\{\begin{bmatrix}1 \\ 2 \\ 3 \end{bmatrix}, \begin{bmatrix}1 \\ 3 \\ 5 \end{bmatrix} \Bigg\}$를  $H$라고 하자. $H$는 $R^3$의 subspace이다.


A. ~~False~~ True

linearly independent한 column vector가 두개이기 때문에 $R^2$의 subspace가 된다.

---



33. 어떤 vector $x$를 subspace $H$로 orthogonal projection 하는 matrix는 여러 개가 나올 수 있다.

A. ~~True~~ False

평면에 projection 된 b hat를 여러 matrix로 표현 가능할 수 있다.

---



34. Least square 문제에서 error, $b - Ax$는 0이 나올 수 없다.

A. False

b가 이미 space A 에 포함되어 있으면 0이 나올 수 있다.

---



35. QR factorization은 square matrix에만 할 수 있다.  

A. False

A가 square matrix가 아니더라도 가능하다

---

